rules:
  deletebyquery:
    - name: CleanAllNameIsJohn
      index: ["articles"]
      cron: "@every 1h"
      body: |
        {
        	"query": {
        		"match":{"author.first_name":"John"}
        	}
        }
    - name: CleanData
      index: ["articles"]
      from: 0
      conflict: proceed
      cron: "@every 1m"
      body: |
        {
        	"query": {
        		"match":{"author.last_name":"ahmet"}
        	}
        }
    - name: CleanFirstNameIsJohnEveryFiveSecond
      index: ["articles"]
      cron: "@every 1m"
      body: |
        {
        	"query": {
        		"match":{"author.first_name":"John"}
        	}
        }
  alert:
    - name: AliceCount
      index: ["articles"]
      cron: "@every 2s"
      query: "Alice"
      since: 15m