it rules:
  deletebyquery:
    - name: CleanAllNameIsJohn
      index: ["articles"]
      cron: "@every 1h"
      body: |
        {
        	"query": {
        		"match":{"author.first_name":"John"}
        	}
        }
    - name: CleanData
      index: ["articles"]
      from: 0
      cron: "@every 5h"
      body: |
        {
        	"query": {
        		"match":{"author.last_name":"Smith"}
        	}
        }
    - name: CleanFirstNameIsJohnEveryFiveSecond,
      index: ["articles"]
      cron: "@every 10s"
      body: |
        {
        	"query": {
        		"match":{"author.first_name":"John"}
        	}
        }